import { CharacterData } from './types';

export const CHARACTERS: CharacterData[] = [
  {
    id: 'alok',
    name: 'DJ Alok',
    title: 'World Renowned Beatmaster',
    avatarColor: '#f59e0b',
    skillName: 'Drop the Beat',
    skillType: 'active',
    skillCooldown: 45,
    skillDescription: 'Creates a 5m rhythmic energy aura that heals 5 HP per second for 10 seconds and boosts sprint speed by +15%.',
    perk: '+15% Sprint Speed & Rapid Healing Aura',
  },
  {
    id: 'chrono',
    name: 'Chrono',
    title: 'Time & Space Defender',
    avatarColor: '#06b6d4',
    skillName: 'Time Turner',
    skillType: 'active',
    skillCooldown: 60,
    skillDescription: 'Deploys an impenetrable spherical force-field that absorbs 600 damage from enemy gunfire.',
    perk: 'Bulletproof Energy Shield Dome',
  },
  {
    id: 'hayato',
    name: 'Hayato',
    title: 'Legendary Samurai Warrior',
    avatarColor: '#ef4444',
    skillName: 'Bushido',
    skillType: 'passive',
    skillCooldown: 0,
    skillDescription: 'The lower your HP falls, the higher your bullet armor penetration becomes (+35% extra damage on wounded state).',
    perk: 'Max Armor Penetration at Low HP',
  },
  {
    id: 'kelly',
    name: 'Kelly "The Swift"',
    title: 'High School Track Star',
    avatarColor: '#eab308',
    skillName: 'Dash',
    skillType: 'passive',
    skillCooldown: 0,
    skillDescription: 'Permanent sprint speed increased by 20% and reload speed increased by 25%.',
    perk: '+20% Permanent Sprint & Fast Reload',
  },
  {
    id: 'wukong',
    name: 'Wukong',
    title: 'The Monkey King',
    avatarColor: '#10b981',
    skillName: 'Camouflage',
    skillType: 'active',
    skillCooldown: 30,
    skillDescription: 'Instantly transforms into a natural foliage bush for 15 seconds, breaking enemy aim-assist and lock-on.',
    perk: 'Stealth Bush Disguise',
  },
];
